In [1]:
from mil.data.datasets import musk1, musk2, protein, elephant, corel_dogs, \
                              ucsb_breast_cancer, web_recommendation_1, birds_brown_creeper, \
                              mnist_bags

import numpy as np

In [2]:
(x_train, y_train), (x_test, y_test) = musk1.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

73 73
19 19
(array([0, 1], dtype=int64), array([37, 36], dtype=int64))
(array([0, 1], dtype=int64), array([ 8, 11], dtype=int64))


In [3]:
(x_train, y_train), (x_test, y_test) = musk2.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

81 81
21 21
(array([0, 1], dtype=int64), array([52, 29], dtype=int64))
(array([0, 1], dtype=int64), array([11, 10], dtype=int64))


In [4]:
(x_train, y_train), (x_test, y_test) = protein.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

154 154
39 39
(array([0, 1], dtype=int64), array([134,  20], dtype=int64))
(array([0, 1], dtype=int64), array([34,  5], dtype=int64))


In [5]:
(x_train, y_train), (x_test, y_test) = elephant.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

160 160
40 40
(array([0, 1], dtype=int64), array([78, 82], dtype=int64))
(array([0, 1], dtype=int64), array([22, 18], dtype=int64))


In [6]:
(x_train, y_train), (x_test, y_test) = corel_dogs.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

1600 1600
400 400
(array([0, 1], dtype=int64), array([1528,   72], dtype=int64))
(array([0, 1], dtype=int64), array([372,  28], dtype=int64))


In [7]:
(x_train, y_train), (x_test, y_test) = ucsb_breast_cancer.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

46 46
12 12
(array([0, 1], dtype=int64), array([25, 21], dtype=int64))
(array([0, 1], dtype=int64), array([7, 5], dtype=int64))


In [8]:
(x_train, y_train), (x_test, y_test) = web_recommendation_1.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

60 60
15 15
(array([0, 1], dtype=int64), array([40, 20], dtype=int64))
(array([0, 1], dtype=int64), array([14,  1], dtype=int64))


In [9]:
(x_train, y_train), (x_test, y_test) = birds_brown_creeper.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

438 438
110 110
(array([0, 1], dtype=int64), array([277, 161], dtype=int64))
(array([0, 1], dtype=int64), array([74, 36], dtype=int64))


# MNIST Bags

In [10]:
(x_train, y_train, y_train_instances), (x_test, y_test, y_test_instances)  = mnist_bags.load()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

200 200
100 100
(array([0, 1]), array([ 72, 128], dtype=int64))
(array([0, 1]), array([30, 70], dtype=int64))


In [11]:
(x_train, y_train, y_train_instances), (x_test, y_test, y_test_instances)  = mnist_bags.load_42()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

200 200
100 100
(array([0, 1]), array([173,  27], dtype=int64))
(array([0, 1]), array([78, 22], dtype=int64))


In [12]:
(x_train, y_train, y_train_instances), (x_test, y_test, y_test_instances)  = mnist_bags.load_2_and_3()

print(len(y_train), len(x_train))
print(len(y_test), len(x_test))

print(np.unique(y_train, return_counts=True))
print(np.unique(y_test, return_counts=True))

200 200
100 100
(array([0, 1]), array([ 83, 117], dtype=int64))
(array([0, 1]), array([36, 64], dtype=int64))
